teams = ["Adoms Kremenchuk",
"Advis-Khutrovyk Khmelnytskyi",
"Ahrotekhservis Sumy",
"Antratsyt Kirovske",
"Arsenal Bila Tserkva",
"Arsenal Kharkiv",
"Arsenal Kyiv",
"Artaniya Ochakiv",
"Askon Yakymivka",
"Avanhard Antratsyt",
"Avanhard Dnipropetrovsk",
"Avanhard Kramatorsk",
"Shakhtar Shakhtarsk",
"Avanhard Stalino",
"Avanhard Zhydachiv",
"Avtomobilist Lviv",
"Avtomobilist Odessa",
"Avtomotor Kharkiv",
"Azot Nyzhnya Horlivka",
"Bakhmach",
"FC Bakhmut",
"BASK Czernowitz",
"Bastion Chornomorsk",
"BChA Korosten",
"Berdyansk",
"Berkut Bedevlya",
"Beskyd Nadvirna",
"Bilshovyk Kyiv",
"Blaho Blahoyeve",
"Borysfen Boryspil",
"Bryz Izmail",
"Bucha",
"Budivelnyk Brovary",
"Budivelnyk Kamianske",
"Budivelnyk Kryvyi Rih",
"Avanhard Ternopil",
"Bukovyna Chernivtsi",
"Burevisnyk Kryvyi Rih",
"Burevisnyk Stalino",
"Chayka-VMS Sevastopol",
"Cherniakhiv",
"Chornohora Ivano-Frankivsk",
"Chornomorets Odesa",
"Chortkiv",
"CSKA Kyiv",
"Dalis Komyshuvakha",
"Danubia Czernowitz",
"Desna Chernihiv",
"Dnipro Cherkasy",
"Dnipro Dnipropetrovsk",
"Dnipro-75 Dnipropetrovsk",
"Dnister Zalischyky",
"Domobudivnyk Chernihiv",
"Dovbush Chernivtsi",
"Dynamo Chernihiv",
"Dynamo Chernivtsi",
"Dynamo Dnipropetrovsk",
"Dynamo Kharkiv",
"Dynamo Khmelnytskyi",
"Dynamo Kryvyi Rih",
"Dynamo Kyiv",
"Dynamo Luhansk",
"Dynamo Lutsk",
"Dynamo Lviv",
"Dynamo Mohyliv-Podilskyi",
"Dynamo Mukachevo",
"Dynamo Mykolaiv",
"Dynamo Odessa",
"Dynamo Poltava",
"Dynamo Rivne",
"Dynamo Saky",
"Dynamo Slovyansk",
"Dynamo Stanislav",
"Dynamo Sumy",
"Dynamo Ternopil",
"Dynamo Vinnytsia",
"Dynamo Zhytomyr",
"Ekran Shostka",
"Elektrometalurh-NZF Nikopol",
"Elektron Ivano-Frankivsk",
"Elektron Romny",
"Enerhetyk Burshtyn",
"Enerhiya Nova Kakhovka",
"Enerhiya Yuzhnoukrainsk",
"ENKO Lutsk",
"Fakel Varva",
"Feniks Kharkiv",
"Feniks-Illichovets Kalinine",
"Frunzenets-Liha-99 Sumy",
"Halychyna Drohobych",
"Halychyna Lviv",
"Haray Zhovkva",
"Hazovyk-KhGV Kharkiv",
"Hazovyk-Khurtovyna Komarno",
"Helferich-Sade Kharkiv",
"Helios Kharkiv",
"Hirnyk Dniprorudne",
"Hirnyk Kryvyi Rih",
"Hirnyk Pavlohrad",
"Hirnyk Rovenky",
"Hirnyk-Illichivets Komsomolske",
"Hirnyk-Sport Horishni Plavni",
"Hoverla Uzhhorod",
"Hran Buzova",
"Hvardiyets Hvardiyske",
"IFC Czernowitz",
"Ihroservice Simferopol",
"Illichivets Mariupol",
"Impuls Kamyanets-Podilskyi",
"Irpin Horenychi",
"Ivan Odessa",
"Jahn Czernowitz",
"Jehuda Tarnopol",
"Junak Drohobycz",
"Kafa-Goleador Feodosiya",
"Kakhovka",
"Kalush",
"Kanatnyi Zavod Kharkiv",
"KAPO Pervomayske",
"Karlivka",
"Karpaty Dubove",
"Karpaty Kamianka-Buzka",
"Karpaty Kolomyia",
"Karpaty Lviv",
"Karpaty Rakhiv",
"Karpaty Yaremche",
"Keramik Baranivka",
"Kharchovyk Kerch",
"Kharchovyk Kherson",
"Kharchovyk Odessa",
"Kharchovyk Simferopol",
"Kharkiv",
"Khartsyzk",
"Khimik Chernihiv",
"Khimik Krasnoperekopsk",
"Khimik Sieverodonetsk",
"Khimmash Korosten",
"Khodak Cherkasy",
"Khutrovyk Tysmenytsia",
"KLS Kyiv",
"Knyazha Shchaslyve",
"Koksokhimichnyi Zavod Makiyivka",
"Kolhosp im. Chapayeva",
"Kolormet Zaporizhya",
"Kolos Buchach",
"Kolos Osokorivka",
"Komunalnyk Luhansk",
"Komunarets Komunarsk",
"Konti Kostyantynivka",
"Korona Sambor",
"Korosten",
"Kosmos Pavlohrad",
"Kovel-Volyn Kovel",
"Krasyliv",
"Kremin Kremenchuk",
"Kresy Tarnopol",
"Kryla Rad Zaporizhya",
"Krymteplytsia Molodizhne",
"Krystal Kherson",
"Krystal Oleksandria",
"Krystal Parkhomivka",
"Kryvbas Kryvyi Rih",
"KSZN Rypne",
"Lada Chernivtsi",
"Lokomotyv Dnipropetrovsk",
"Lokomotyv Donetsk",
"Lokomotyv Dvorichna",
"Lokomotyv Kharkiv",
"Lokomotyv Kotovsk",
"Lokomotyv Kupyansk",
"Lokomotyv Kyiv",
"Lokomotyv Odessa",
"Lokomotyv Poltava",
"Lokomotyv Rivne",
"Lokomotyv Synelnykove",
"Lokomotyv Yasynuvata",
"Lokomotyv Zaporizhya",
"Lozova",
"Luzhany",
"Lviv",
"LVVPU Lviv",
"Lysychansk",
"Maccabi Kyiv",
"Makiyivvuhillya Makiyivka",
"Mashynobudivnyk Druzhkivka",
"Mashynobudivnyk Kyiv",
"Mebelnyk Chernivtsi",
"Metal Dnipropetrovsk",
"Metalist Kharkiv",
"Metalist Sevastopol",
"Metalurh Donetsk",
"Metalurh Kupyansk",
"Metalurh Novomoskovsk",
"Metalurh Zaporizhya",
"Meteor Dnipropetrovsk",
"MHK Voznesensk",
"Mistran Odessa",
"MlynKov Mlyniv",
"Molniya Kharkiv",
"Molniya Sieverodonetsk",
"Morshyn",
"Mukachevo",
"Mykolaiv",
"Mykolaiv",
"Myr Hornostayivka",
"Myrhorod",
"Nafkom Brovary",
"Naftokhimik Kremenchuk",
"Naftovyk Dolyna",
"Naftovyk-Ukrnafta Okhtyrka",
"Nizhyn",
"Nove Zhyttia Andriivka",
"Nyva Bershad",
"Nyva Ternopil",
"Nyva Vinnytsia",
"Nyva-Kosmos Myronivka",
"OBAK Odessa",
"Obolon Kyiv",
"ODEK Orzhiv",
"Odeskyi HF Odessa",
"Odessa",
"Odessa",
"Okean Kerch",
"Oleksandriya",
"Olimp Starobilsk",
"Olimpik Donetsk",
"Olimpik Kharkiv",
"Olimpik Kirovohrad",
"Olkom Melitopol",
"Oskil Kupyansk",
"Palmira Odessa",
"Papirnyk Malyn",
"Perechyn",
"Pervomaysk",
"Pivdenstal Yenakiieve",
"Podillia Tarnopil",
"Podillya Kamyanets-Podilskyi",
"Podillya Khmelnytskyi",
"Pokuttya Kolomyia",
"Polissya Zhytomyr",
"Politekhniky Kyiv",
"Poltava",
"Portovyk Illichivsk",
"Probiy Horodenka",
"Prohres Berdychiv",
"Prometei Dniprodzerzhynsk",
"Prometei Dniprodzerzhynsk",
"Prykarpattya Ivano-Frankivsk",
"Putrivka",
"RadTorhSluzhbovtsi Kyiv",
"Ratusha Kamyanets-Podilskyi",
"Rava Rava-Ruska",
"Real Odessa",
"Real Pharm Yuzhne",
"Rohatyn",
"Ros Bila Tserkva",
"Rot-Front Kyiv",
"Rot-Front Poltava",
"Rud Zhytomyr",
"Rukh Kyiv",
"Rus Khust",
"Rybak-Dorozhnyk Odessa",
"Sambir",
"SDYuShOR-Metalurh Zaporizhya",
"Shakhta Ukraina Ukrainsk",
"Shakhtar Chervonohrad",
"Shakhtar Donetsk",
"Shakhtar Dzerzhynsk",
"Shakhtar Horlivka",
"Shakhtar Kirovsk",
"Shakhtar Konotop",
"Shakhtar Korostyshiv",
"Shakhtar Krasnyi Luch",
"Shakhtar Luhansk",
"Shakhtar Makiyivka",
"Shakhtar Novovolynsk",
"Shakhtar Rowenky",
"Shakhtar Rutchenkove",
"Shakhtar Smolyanka",
"Shakhtar Snizhne",
"Shakhtar Sverdlovsk",
"Sharhorod",
"Sheremetyevskyi HS Odessa",
"Shkirtrest Odessa",
"Shturm Kharkiv",
"Silmash Kharkiv",
"Sirius Kryvyi Rih",
"SKA Lviv",
"SKA Odessa",
"SKAD-Yalpuh Bolhrad",
"Skala Stryi",
"Skala Stryi (2004)",
"SKA-Lotto Odessa",
"SKChF Sevastopol",
"Skhid Kyiv",
"SKIF Kyiv",
"Skify Lviv",
"Slavutych",
"Slavutych Cherkasy",
"Slovkhlib Slovyansk",
"Sluch Berezne",
"Sokal",
"Sokil Berezhany",
"Sokil Lviv",
"Sokil Radyvyliv",
"Sokil Zolochiv",
"Sovignon Tayirove",
"Spartak Chernihiv",
"Spartak Chernivtsi",
"Spartak Dnipropetrovsk",
"Spartak Ivano-Frankivsk",
"Spartak Kharkiv",
"Spartak Korosten",
"Spartak Kyiv",
"Spartak Lviv",
"Spartak Poltava",
"Spartak Sumy",
"Spartak Vinnytsia",
"Sport Kyiv",
"Sporting-Klub Odessa",
"Sportinvest Kryvyi Rih",
"Stakhanov",
"Stal Alchevsk",
"Stal Kamianske",
"Stal Dnipropetrovsk",
"Stal Kryvyi Rih",
"Stalinets Kharkiv",
"Start Chuhuiv",
"Start Kyiv",
"Stroitel Pripyat",
"Strzelec Janowa Dolina",
"Strzelec Kowel",
"Sula Lubny",
"Sumy",
"Suputnyk Poltava",
"Surozh Sudak",
"Tavriya Novotroitske",
"Tavriya Simferopol",
"Tekhnikum Fizkultury Dnipropetrovsk",
"Temp Kyiv",
"Temp Shepetivka",
"Temp Vinnytsia",
"Ternopil",
"Torez",
"Torpedo Kharkiv",
"Torpedo Mykolaiv",
"Torpedo Odessa",
"Torpedo Zaporizhya",
"Troyanda-Ekspres Hirka Polonka",
"Tsukrovyky Sumy",
"Tyras-2500 Bilhorod-Dnistrovskyi",
"Tytan Armyansk",
"Tytan Donetsk",
"Tytan Vilnohirsk",
"Tytan Zaporizhya",
"Uholyok Myrnohrad",
"Uholyok Krasnoarmiysk",
"UkrAhroKom Holovkivka",
"Ukraina Lviv",
"Vahonobudivnyk Kremenchuk",
"Vatra Drohobych",
"Veres Rivne",
"Viktor Zaporizhya",
"Vodnyk Kyiv",
"Vodnyk Mykolaiv",
"Vodnyk Odessa",
"Volyn Lutsk",
"Vorskla Poltava",
"VPS Kharkiv",
"Vykhor Dnipropetrovsk",
"Vympel Kyiv",
"WKS Dubno",
"Yalos Yalta",
"Yalynka Velykyi Bychkiv",
"Yavir Smila",
"Yednist' Plysky",
"Zavod im. K.Libknechta Dnipropetrovsk",
"Zavod im. Kominternu Dnipropetrovsk",
"Zavod im. Lenina Krasnohorivka",
"Zdorovya Kharkiv",
"Zenit Boyarka",
"Zenit Kharkiv",
"Zenit Kyiv",
"Zenit Stalino",
"Zhemchuzhyna Yalta",
"Zhytomyr",
"Zhytychi Zhytomyr",
"Zirka Berdychiv",
"Zirka Kropyvnytskyi",
"Znannya Kherson",
"Zorya Khorostkiv",
"Zorya Luhansk",
"Zvyahel-750 Novohrad-Volynskyi",
]